version: '2.0'
services:
  rasa:
    image: rasa/rasa:1.10.26-full
    ports:
      - 5005:5005
    volumes:
      - ./rasa:/app
    command: run --enable-api
  rhasspy:
    ports:
        - '12101:12101'
    depends_on:
      - rasa
      - mosquitto
    volumes:
        - '.config/rhasspy/profiles:/profiles'
    image: rhasspy/rhasspy
    command: --user-profiles /profiles --profile en
  mosquitto:
    ports:
      - '1883:1883'
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/conf:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  intent_handler:
    build: ./mqtt_scripts/intent_handler
    depends_on:
     - 'mosquitto'
    volumes: ["./mqtt_scripts/intent_handler:/intent_handler"]
  ui:
    build: ./ui
    ports: ["5000:5000"]
    volumes: ["./ui:/ui"]
    depends_on:
     - 'mosquitto'
    