services:
  dialogue:
    command: --debug --host mosquitto --port 1883 --site-id master --site-id sattelite
      --session-timeout 30 --sound wake /usr/lib/rhasspy/etc/wav/beep_hi.wav --sound
      recorded /usr/lib/rhasspy/etc/wav/beep_lo.wav --sound error /usr/lib/rhasspy/etc/wav/beep_error.wav
      --volume 1 --min-asr-confidence 0 --say-chars-per-second 33 --sound-suffix .wav
      --sound-suffix .mp3 --sound-suffix .ogg --sound-suffix .flac
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-dialogue-hermes
    tty: true
  intent_recognition:
    command: --rasa-url http://rasa:5005/ --debug --host mosquitto --port 1883 --site-id
      master --site-id sattelite --rasa-project rhasspy --examples-path /profiles/en/intent_examples.md
      --replace-numbers --number-language en_US --casing lower
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-rasa-nlu-hermes
    tty: true
    volumes:
    - /profiles:/profiles
  speech_to_text:
    command: --model-type nnet3 --model-dir /profiles/en/kaldi/model --graph-dir /profiles/en/kaldi/model/graph
      --debug --host mosquitto --port 1883 --site-id master --site-id sattelite --dictionary
      /profiles/en/kaldi/dictionary.txt --language-model /profiles/en/kaldi/language_model.txt
      --language-model-type text_fst --base-dictionary /profiles/en/kaldi/base_dictionary.txt
      --base-dictionary /profiles/en/kaldi_custom_words.txt --dictionary-casing lower
      --g2p-model /profiles/en/kaldi/g2p.fst --unknown-words /profiles/en/kaldi_unknown_words.txt
      --base-language-model-fst /profiles/en/kaldi/base_language_model.fst --base-language-model-weight
      0.5 --mixed-language-model-fst /profiles/en/kaldi/mixed.fst --frequent-words
      /usr/lib/rhasspy/rhasspy-profile/rhasspyprofile/profiles/en/frequent_words.txt
      --max-frequent-words 100 --max-unknown-words 8 --unknown-words-probability 1e-05
      --unknown-token '<unk>' --silence-probability 0.5 --cancel-word '' --cancel-probability
      0.01 --voice-skip-seconds 0 --voice-min-seconds 1 --voice-max-seconds 20 --voice-speech-seconds
      0.3 --voice-silence-seconds 0.5 --voice-before-seconds 0.5 --voice-sensitivity
      1 --voice-silence-method vad_only
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-asr-kaldi-hermes
    tty: true
    volumes:
    - /profiles:/profiles
  text_to_speech:
    command: --tts-command 'nanotts -v {lang} -o {file}' --temporary-wav --text-on-stdin
      --volume 1 --debug --host mosquitto --port 1883 --site-id master --site-id sattelite
      --language en-US
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-tts-cli-hermes
    tty: true
version: '2'
